### ISSUE TITLE
DATA: Determine centroid of each disputed place

### ISSUE THREAD

**Issue by alykat** [alykat/map-disputes#2]

**Comment by gwezerek** [comment]
Hit wall with this one. Can export the centroid layr from QGIS, but the coordinates are Cartesian. The layer and system projections are correct (Mercator 84, or something along those lines), and even re-projecting and saving doesn't change the fact that I can't get the X and Y coords as lat and long. @alykat, can we take a crack at it together tomorrow morning? Maybe I'm missing something.

**Comment by gwezerek** [comment]
We're doing this manually. Sadly I wasn't able to figure this out, in any case.
